language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"

env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  
deploy:
  provider: script
  script: netlify deploy --site=$NETLIFY_SITEID --auth=$NETLIFY_TOKEN --dir=public --prod
  skip_cleanup: true
  on:
    branch: master
